# Generated by Django 3.2.6 on 2021-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics & Appliances', 'Electronics & Appliances'), ('Vehicles', 'Vehicles'), ('Clothings', 'Clothings'), ('Stationary', 'Stationary'), ('Pets', 'Pets'), ('Beauty', 'Beauty'), ('miscellaneous', 'miscellaneous')], default='', max_length=50),
        ),
    ]
