# Generated by Django 3.2.6 on 2021-10-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20211010_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 44, 59, 3312)),
        ),
    ]
