# Generated by Django 3.2.6 on 2021-10-11 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_auto_20211011_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquestion',
            name='answered_date',
        ),
        migrations.RemoveField(
            model_name='postquestion',
            name='answered_time',
        ),
        migrations.RemoveField(
            model_name='postquestion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='postquestion',
            name='time',
        ),
        migrations.AlterField(
            model_name='reserved',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 21, 19, 31, 858202)),
        ),
    ]
