# Generated by Django 3.2.6 on 2021-10-20 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_image'),
        ('Posts', '0012_auto_20211020_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_amount', models.CharField(max_length=25)),
                ('isReserved', models.BooleanField(default=False)),
                ('reserve_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 19, 15, 19899))),
                ('reserve_payment_id', models.CharField(max_length=100)),
                ('reserve_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserved',
        ),
    ]
