# Generated by Django 3.2.6 on 2021-12-02 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_auto_20211020_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 0, 7, 42, 702121)),
        ),
    ]
