# Generated by Django 3.2.6 on 2022-04-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0014_auto_20211203_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 14, 49, 42, 442119)),
        ),
    ]
