# Generated by Django 3.2.6 on 2022-04-09 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0015_alter_reserve_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 13, 10, 3, 644184)),
        ),
    ]
