# Generated by Django 3.2.6 on 2026-01-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_user_id'),
        ('Profile', '0004_profile_coins'),
    ]

    operations = [
    ]
